
# Setup
title:            h3LLsins's Note
tagline:          'Hello world'
baseurl:          https://h3LLsins.github.io

author:
  name:           

paginate:         7

markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty
